In [13]:
pip install pandas

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd

In [15]:
%pip install openpyxl
import openpyxl

Requirement already satisfied: openpyxl in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

1. Create the DataFrame.
2. Display the first 3 rows.
3. Display the last 2 rows.
4. Display only the Name column.
5. Display Name and Marks columns.
6. Find the shape of the DataFrame.
7. Display all column names.
8. Display data types of each column.
9. Display summary statistics.
10. Find the maximum marks.
11. Find the minimum marks.
12. Find the average age.
13. Count the total number of students.
14. Display DataFrame information.
15. Save the DataFrame as students.xlsx.

In [16]:
df = pd.read_excel(r"./asspandas.xlsx")
print(df)

   RollNo    Name   Age    City   Marks
0       101   Amit   20   Delhi      85
1       102  Priya   21  Mumbai      90
2       103  Rahul   19    Pune      78
3       104  Sneha   22   Delhi      88
4       105  Karan   20  Jaipur      76

In [17]:
# display the 3 rows

df.head(3)

   RollNo    Name   Age    City   Marks
0       101   Amit   20   Delhi      85
1       102  Priya   21  Mumbai      90
2       103  Rahul   19    Pune      78

In [19]:
# display the last 2 rows
df.tail(2)

   RollNo    Name   Age    City   Marks
3       104  Sneha   22   Delhi      88
4       105  Karan   20  Jaipur      76

In [22]:
# fetch specific column

print(df['Name '])

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
Name: Name , dtype: object

In [ ]:
# fetch specific columns
print(df[['Name ', ' Marks']]) # after name space is there so we have to write it as it is and same for marks column(before)

   Name    Marks
0   Amit      85
1  Priya      90
2  Rahul      78
3  Sneha      88
4  Karan      76

In [42]:
df.shape

(5, 5)

In [43]:
df.columns

Index(['RollNo  ', 'Name ', 'Age', 'City', ' Marks'], dtype='object')

In [ ]:
# display the data types of each column

print(df.dtypes)

RollNo       int64
Name        object
Age          int64
City        object
 Marks       int64
dtype: object

In [46]:
# display summary statistics of the data frame

print(df.describe())

         RollNo          Age     Marks
count    5.000000   5.000000   5.00000
mean   103.000000  20.400000  83.40000
std      1.581139   1.140175   6.14817
min    101.000000  19.000000  76.00000
25%    102.000000  20.000000  78.00000
50%    103.000000  20.000000  85.00000
75%    104.000000  21.000000  88.00000
max    105.000000  22.000000  90.00000

In [47]:
print(df[' Marks'].max())

90

In [48]:
print(df[' Marks'].min())

76

In [50]:
df1 = df['Age'].mean()
print(df1)

20.4

In [ ]:
# count total number of students in the data frame

print(df.shape[0]) # 0 index means rows and by this we can count the total number of students in the data frame

5

In [54]:
# display dataframe information

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   RollNo    5 non-null      int64
 1   Name      5 non-null      object
 2   Age       5 non-null      int64
 3   City      5 non-null      object
 4    Marks    5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes
None

In [56]:
# save data frame to a new excel file

df.to_excel('pandas_datanewcreate.xlsx', index=False)