# Name : Kirti Singh

# Roll no. : 1230432347

In [1]:
import pandas as pd

df = pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Reyansh","Shaurya","Krishna","Ishaan","Kabir",
             "Rohan","Kunal","Samar","Yash","Dev","Ayaan","Rudra","Om","Aryan","Parth"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})

print(df)
df.to_csv("student_info.csv")                       # df.to_csv("student_info.csv", index=False)  # to save without index in the csv file
print("successfully saved to csv file")

# to see random record 
df.sample()

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500
successfully saved to csv file

    ID Name  Age  City  Marks Department  Salary
14  15  Dev   19  Agra     87         CS   30500

📘 🔹 Basic Level (1–10)
Show all students whose Marks > 85

Show all students whose Age is 20

Show all students who live in Delhi

Show all students who live in Mumbai

Show all students whose Salary > 35000

Show all students whose Marks < 80

Show all students whose Age > 21

Show all students whose Department is CS

Show all students whose Department is IT

Show all students whose City is Lucknow
📘 🔹 Medium Level (11–20)
Show students whose Marks > 80 AND Age < 21

Show students from Delhi AND Marks > 85

Show students from Mumbai OR Pune

Show students NOT from Lucknow

Show students whose Marks between 80 and 90

Show students whose Department is CS OR EC

Show students whose Salary > 32000 AND Department is IT

Show students whose Age is 21 OR Marks > 90

Show students whose City is Delhi, Mumbai, or Lucknow

Show students whose Marks > 85 AND Age >= 20

In [2]:
# Show all Student whose age is 20

df[df['Age'] == 20]

    ID    Name  Age    City  Marks Department  Salary
1    2  Vivaan   20   Delhi     90         IT   32000
4    5   Arjun   20  Kanpur     92         EC   40000
9   10   Kabir   20  Mumbai     84         IT   34000
13  14    Yash   20   Noida     91         EC   41000
17  18      Om   20  Mumbai     86         CS   31500

In [3]:
# Show students whose City is Delhi

df[df['City'] == 'Delhi']

    ID    Name  Age   City  Marks Department  Salary
1    2  Vivaan   20  Delhi     90         IT   32000
8    9  Ishaan   19  Delhi     89         CS   31000
16  17   Rudra   22  Delhi     83         EC   38000

In [4]:
# Show students whose City is Mumbai

df[df['City'] == 'Mumbai']

    ID    Name  Age    City  Marks Department  Salary
2    3  Aditya   21  Mumbai     78         CS   28000
9   10   Kabir   20  Mumbai     84         IT   34000
17  18      Om   20  Mumbai     86         CS   31500

In [5]:
# Show students whose Salary is greater than 35000

df[df['Salary'] > 35000]

    ID     Name  Age     City  Marks Department  Salary
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [6]:
# Show students whose Marks < 80

df[df['Marks'] < 80]

    ID     Name  Age     City  Marks Department  Salary
2    3   Aditya   21   Mumbai     78         CS   28000
5    6  Reyansh   23    Noida     76         CS   27000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
15  16    Ayaan   21   Jaipur     79         IT   32500

In [7]:
# Show students whose Age is greater than 21

df[df['Age'] >21]

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [8]:
# Show students whose Department is CS

df[df['Department'] == 'CS']

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
2    3   Aditya   21   Mumbai     78         CS   28000
5    6  Reyansh   23    Noida     76         CS   27000
8    9   Ishaan   19    Delhi     89         CS   31000
11  12    Kunal   22  Lucknow     77         CS   30000
14  15      Dev   19     Agra     87         CS   30500
17  18       Om   20   Mumbai     86         CS   31500

In [9]:
# Show students whose Department is IT

df[df['Department'] == 'IT']

    ID     Name  Age    City  Marks Department  Salary
1    2   Vivaan   20   Delhi     90         IT   32000
3    4   Vihaan   22    Pune     88         IT   35000
6    7  Shaurya   21    Agra     81         IT   33000
9   10    Kabir   20  Mumbai     84         IT   34000
12  13    Samar   23  Kanpur     80         IT   36000
15  16    Ayaan   21  Jaipur     79         IT   32500
18  19    Aryan   21    Pune     90         IT   34500

In [10]:
# Show students whose city is Lucknow

df[df['City'] == 'Lucknow']

    ID   Name  Age     City  Marks Department  Salary
0    1  Aarav   19  Lucknow     85         CS   30000
11  12  Kunal   22  Lucknow     77         CS   30000
19  20  Parth   23  Lucknow     88         EC   39500

In [11]:
# Show students from Delhi AND Marks > 85

df[(df['City'] == 'Delhi') & (df['Marks'] > 85)]

   ID    Name  Age   City  Marks Department  Salary
1   2  Vivaan   20  Delhi     90         IT   32000
8   9  Ishaan   19  Delhi     89         CS   31000

In [12]:
#Show students from Mumbai OR Pune 

df[(df['City'] == 'Mumbai') | (df['City'] == 'Pune')]

    ID    Name  Age    City  Marks Department  Salary
2    3  Aditya   21  Mumbai     78         CS   28000
3    4  Vihaan   22    Pune     88         IT   35000
9   10   Kabir   20  Mumbai     84         IT   34000
10  11   Rohan   21    Pune     73         EC   29000
17  18      Om   20  Mumbai     86         CS   31500
18  19   Aryan   21    Pune     90         IT   34500

In [13]:
# Show students NOT from Lucknow

df[df['City'] != 'Lucknow']

    ID     Name  Age    City  Marks Department  Salary
1    2   Vivaan   20   Delhi     90         IT   32000
2    3   Aditya   21  Mumbai     78         CS   28000
3    4   Vihaan   22    Pune     88         IT   35000
4    5    Arjun   20  Kanpur     92         EC   40000
5    6  Reyansh   23   Noida     76         CS   27000
6    7  Shaurya   21    Agra     81         IT   33000
7    8  Krishna   22  Jaipur     95         EC   42000
8    9   Ishaan   19   Delhi     89         CS   31000
9   10    Kabir   20  Mumbai     84         IT   34000
10  11    Rohan   21    Pune     73         EC   29000
12  13    Samar   23  Kanpur     80         IT   36000
13  14     Yash   20   Noida     91         EC   41000
14  15      Dev   19    Agra     87         CS   30500
15  16    Ayaan   21  Jaipur     79         IT   32500
16  17    Rudra   22   Delhi     83         EC   38000
17  18       Om   20  Mumbai     86         CS   31500
18  19    Aryan   21    Pune     90         IT   34500

In [14]:
# Show students whose Marks between 80 and 90

df[(df['Marks'] >= 80) & (df['Marks'] <= 90)]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
3    4   Vihaan   22     Pune     88         IT   35000
6    7  Shaurya   21     Agra     81         IT   33000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
12  13    Samar   23   Kanpur     80         IT   36000
14  15      Dev   19     Agra     87         CS   30500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500

In [15]:
# Show students whose Department is CS OR EC

df[(df['Department'] == 'CS') | (df['Department'] == 'EC')]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
2    3   Aditya   21   Mumbai     78         CS   28000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
19  20    Parth   23  Lucknow     88         EC   39500

In [16]:
# Show students whose Salary > 32000 AND Department is IT

df[(df['Salary']> 32000) & (df['Department'] == 'IT')]

    ID     Name  Age    City  Marks Department  Salary
3    4   Vihaan   22    Pune     88         IT   35000
6    7  Shaurya   21    Agra     81         IT   33000
9   10    Kabir   20  Mumbai     84         IT   34000
12  13    Samar   23  Kanpur     80         IT   36000
15  16    Ayaan   21  Jaipur     79         IT   32500
18  19    Aryan   21    Pune     90         IT   34500

In [17]:
# Show students whose Age is 21 OR Marks > 90
df[(df['Age'] >21) | (df['Marks'] > 90)]

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [18]:
# Show students whose City is Delhi, Mumbai, or Lucknow

df[(df['City'] == 'Delhi') | (df['City'] == 'Mumbai') | (df['City'] == 'Lucknow')]

    ID    Name  Age     City  Marks Department  Salary
0    1   Aarav   19  Lucknow     85         CS   30000
1    2  Vivaan   20    Delhi     90         IT   32000
2    3  Aditya   21   Mumbai     78         CS   28000
8    9  Ishaan   19    Delhi     89         CS   31000
9   10   Kabir   20   Mumbai     84         IT   34000
11  12   Kunal   22  Lucknow     77         CS   30000
16  17   Rudra   22    Delhi     83         EC   38000
17  18      Om   20   Mumbai     86         CS   31500
19  20   Parth   23  Lucknow     88         EC   39500

In [19]:
# Show students whose Marks > 85 AND Age >= 20

df[(df['Marks'] > 85) & (df['Age'] >= 20)]

    ID     Name  Age     City  Marks Department  Salary
1    2   Vivaan   20    Delhi     90         IT   32000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000
13  14     Yash   20    Noida     91         EC   41000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500