In [3]:
import pandas as pd

df = pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Reyansh","Shaurya","Krishna","Ishaan","Kabir",
             "Rohan","Kunal","Samar","Yash","Dev","Ayaan","Rudra","Om","Aryan","Parth"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})

print(df)
df.to_csv("student_info.csv")                       # df.to_csv("student_info.csv", index=False)  # to save without index in the csv file
print("successfully saved to csv file")

# to see random record 
df.sample()

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500
successfully saved to csv file

    ID   Name  Age     City  Marks Department  Salary
19  20  Parth   23  Lucknow     88         EC   39500

In [25]:
df.head(5)

   ID    Name  Age     City  Marks Department  Salary
0   1   Aarav   19  Lucknow     85         CS   30000
1   2  Vivaan   20    Delhi     90         IT   32000
2   3  Aditya   21   Mumbai     78         CS   28000
3   4  Vihaan   22     Pune     88         IT   35000
4   5   Arjun   20   Kanpur     92         EC   40000

In [27]:
df.tail(7)

    ID   Name  Age     City  Marks Department  Salary
13  14   Yash   20    Noida     91         EC   41000
14  15    Dev   19     Agra     87         CS   30500
15  16  Ayaan   21   Jaipur     79         IT   32500
16  17  Rudra   22    Delhi     83         EC   38000
17  18     Om   20   Mumbai     86         CS   31500
18  19  Aryan   21     Pune     90         IT   34500
19  20  Parth   23  Lucknow     88         EC   39500

In [28]:
df.shape

(20, 7)

In [29]:
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks', 'Department', 'Salary'], dtype='object')

In [30]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [31]:
df.dtypes

ID             int64
Name          object
Age            int64
City          object
Marks          int64
Department    object
Salary         int64
dtype: object

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   City        20 non-null     object
 4   Marks       20 non-null     int64
 5   Department  20 non-null     object
 6   Salary      20 non-null     int64
dtypes: int64(4), object(3)
memory usage: 1.2+ KB

In [33]:
df.describe

<bound method NDFrame.describe of     ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500>

In [34]:
print(pd.read_csv("student_info.csv"))

    Unnamed: 0  ID     Name  Age     City  Marks Department  Salary
0            0   1    Aarav   19  Lucknow     85         CS   30000
1            1   2   Vivaan   20    Delhi     90         IT   32000
2            2   3   Aditya   21   Mumbai     78         CS   28000
3            3   4   Vihaan   22     Pune     88         IT   35000
4            4   5    Arjun   20   Kanpur     92         EC   40000
5            5   6  Reyansh   23    Noida     76         CS   27000
6            6   7  Shaurya   21     Agra     81         IT   33000
7            7   8  Krishna   22   Jaipur     95         EC   42000
8            8   9   Ishaan   19    Delhi     89         CS   31000
9            9  10    Kabir   20   Mumbai     84         IT   34000
10          10  11    Rohan   21     Pune     73         EC   29000
11          11  12    Kunal   22  Lucknow     77         CS   30000
12          12  13    Samar   23   Kanpur     80         IT   36000
13          13  14     Yash   20    Noida     91         EC   41000
14          14  15      Dev   19     Agra     87         CS   30500
15          15  16    Ayaan   21   Jaipur     79         IT   32500
16          16  17    Rudra   22    Delhi     83         EC   38000
17          17  18       Om   20   Mumbai     86         CS   31500
18          18  19    Aryan   21     Pune     90         IT   34500
19          19  20    Parth   23  Lucknow     88         EC   39500

In [5]:
print(df.iloc[5], "\n")  # to see first record 
print(df.iloc[-1])  # to see last record

ID                  6
Name          Reyansh
Age                23
City            Noida
Marks              76
Department         CS
Salary          27000
Name: 5, dtype: object

ID                 20
Name            Parth
Age                23
City          Lucknow
Marks              88
Department         EC
Salary          39500
Name: 19, dtype: object

In [40]:
print(df.iloc[10:16])  # to see records from 10 to 14

    ID   Name  Age     City  Marks Department  Salary
10  11  Rohan   21     Pune     73         EC   29000
11  12  Kunal   22  Lucknow     77         CS   30000
12  13  Samar   23   Kanpur     80         IT   36000
13  14   Yash   20    Noida     91         EC   41000
14  15    Dev   19     Agra     87         CS   30500
15  16  Ayaan   21   Jaipur     79         IT   32500

In [41]:
print(df.loc[df['Age'] > 21])  # to see records where age is greater than 21

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [ ]:
# boolean indexing filter rows based on condition

bool_index = df['Age'] > 21
print(df[bool_index])  # to see records where age is greater than 21

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [ ]:
# sorting and indexing

df.sort_values(by='Salary', ascending=False)  # sort by salary in descending order and if we write inplace=True then it will change the original dataframe

    ID     Name  Age     City  Marks Department  Salary
7    8  Krishna   22   Jaipur     95         EC   42000
13  14     Yash   20    Noida     91         EC   41000
4    5    Arjun   20   Kanpur     92         EC   40000
19  20    Parth   23  Lucknow     88         EC   39500
16  17    Rudra   22    Delhi     83         EC   38000
12  13    Samar   23   Kanpur     80         IT   36000
3    4   Vihaan   22     Pune     88         IT   35000
18  19    Aryan   21     Pune     90         IT   34500
9   10    Kabir   20   Mumbai     84         IT   34000
6    7  Shaurya   21     Agra     81         IT   33000
15  16    Ayaan   21   Jaipur     79         IT   32500
1    2   Vivaan   20    Delhi     90         IT   32000
17  18       Om   20   Mumbai     86         CS   31500
8    9   Ishaan   19    Delhi     89         CS   31000
14  15      Dev   19     Agra     87         CS   30500
0    1    Aarav   19  Lucknow     85         CS   30000
11  12    Kunal   22  Lucknow     77         CS   30000
10  11    Rohan   21     Pune     73         EC   29000
2    3   Aditya   21   Mumbai     78         CS   28000
5    6  Reyansh   23    Noida     76         CS   27000

In [49]:
df.sort_index()

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500