In [10]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Riya",None,"Karan","Priya","Rahul","Neha",None,
             "Vikas","Pooja","Ankit","Simran","Rohit",None,"Kajal",
             "Deepak","Meena","Arjun","Nisha",None],

    "Age": [20,21,np.nan,22,19,23,21,20,np.nan,22,
            24,23,21,20,22,np.nan,19,21,23,20],

    "City": ["Delhi","Mumbai","Pune",None,"Jaipur","Delhi","Mumbai",
             "Pune","Delhi",None,"Jaipur","Mumbai","Delhi","Pune",
             None,"Delhi","Mumbai","Jaipur","Pune","Delhi"],

    "Marks": [85,90,78,np.nan,88,76,91,82,95,np.nan,
              80,84,79,92,87,75,np.nan,89,81,93]
})

print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [11]:
df.isnull() # it will show all the record (True means null value and False means not null value)

    Student_ID   Name    Age   City  Marks
0        False  False  False  False  False
1        False  False  False  False  False
2        False   True   True  False  False
3        False  False  False   True   True
4        False  False  False  False  False
5        False  False  False  False  False
6        False  False  False  False  False
7        False   True  False  False  False
8        False  False   True  False  False
9        False  False  False   True   True
10       False  False  False  False  False
11       False  False  False  False  False
12       False  False  False  False  False
13       False   True  False  False  False
14       False  False  False   True  False
15       False  False   True  False  False
16       False  False  False  False   True
17       False  False  False  False  False
18       False  False  False  False  False
19       False   True  False  False  False

In [12]:
df.isnull().sum()  # to see how many null values are there in each column

Student_ID    0
Name          4
Age           3
City          3
Marks         3
dtype: int64

In [13]:
df.dropna()  # to drop all the records which have null values in any column but in this the record which is null is not deleted

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [14]:
print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [16]:
df.dropna(inplace=True)  # to drop all the records which have null values in any column and it will delete the record which is null
print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [52]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Riya",None,"Karan","Priya","Rahul","Neha",None,
             "Vikas","Pooja","Ankit","Simran","Rohit",None,"Kajal",
             "Deepak","Meena","Arjun","Nisha",None],

    "Age": [20,21,np.nan,22,19,23,21,20,np.nan,22,
            24,23,21,20,22,np.nan,19,21,23,20],

    "City": ["Delhi","Mumbai","Pune",None,"Jaipur","Delhi","Mumbai",
             "Pune","Delhi",None,"Jaipur","Mumbai","Delhi","Pune",
             None,"Delhi","Mumbai","Jaipur","Pune","Delhi"],

    "Marks": [85,90,78,np.nan,88,76,91,82,95,np.nan,
              80,84,79,92,87,75,np.nan,89,81,93]
})

print(df1)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [54]:
df1.fillna(value={'Name': 'Unknown', 'Age': 0, 'City': 'Not Avialable', 'Marks': 0}, inplace=True)  
print(df1)

    Student_ID     Name   Age           City  Marks
0          101     Aman  20.0          Delhi   85.0
1          102     Riya  21.0         Mumbai   90.0
2          103  Unknown   0.0           Pune   78.0
3          104    Karan  22.0  Not Avialable    0.0
4          105    Priya  19.0         Jaipur   88.0
5          106    Rahul  23.0          Delhi   76.0
6          107     Neha  21.0         Mumbai   91.0
7          108  Unknown  20.0           Pune   82.0
8          109    Vikas   0.0          Delhi   95.0
9          110    Pooja  22.0  Not Avialable    0.0
10         111    Ankit  24.0         Jaipur   80.0
11         112   Simran  23.0         Mumbai   84.0
12         113    Rohit  21.0          Delhi   79.0
13         114  Unknown  20.0           Pune   92.0
14         115    Kajal  22.0  Not Avialable   87.0
15         116   Deepak   0.0          Delhi   75.0
16         117    Meena  19.0         Mumbai    0.0
17         118    Arjun  21.0         Jaipur   89.0
18         119    Nisha  23.0           Pune   81.0
19         120  Unknown  20.0          Delhi   93.0

In [59]:
mean_marks = df1['Marks'].mean()# to find the mean of marks column
print("Mean of Marks column:", mean_marks)

Mean of Marks column: 83.0875

In [60]:
# replace....

df1['Marks'].replace(to_replace= 0 , value = mean_marks, inplace=True)  # to replace the 0 value with mean of marks column
print(df1)

    Student_ID     Name   Age           City  Marks
0          101     Aman  20.0          Delhi  85.00
1          102     Riya  21.0         Mumbai  90.00
2          103  Unknown   0.0           Pune  78.00
3          104    Karan  22.0  Not Avialable  72.25
4          105    Priya  19.0         Jaipur  88.00
5          106    Rahul  23.0          Delhi  76.00
6          107     Neha  21.0         Mumbai  91.00
7          108  Unknown  20.0           Pune  82.00
8          109    Vikas   0.0          Delhi  95.00
9          110    Pooja  22.0  Not Avialable  72.25
10         111    Ankit  24.0         Jaipur  80.00
11         112   Simran  23.0         Mumbai  84.00
12         113    Rohit  21.0          Delhi  79.00
13         114  Unknown  20.0           Pune  92.00
14         115    Kajal  22.0  Not Avialable  87.00
15         116   Deepak   0.0          Delhi  75.00
16         117    Meena  19.0         Mumbai  72.25
17         118    Arjun  21.0         Jaipur  89.00
18         119    Nisha  23.0           Pune  81.00
19         120  Unknown  20.0          Delhi  93.00

C:\Users\asus\AppData\Local\Temp\ipykernel_8296\715374462.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Marks'].replace(to_replace= 0 , value = mean_marks, inplace=True)  # to replace the 0 value with mean of marks column