### PANDAS:

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

series and dataframe (to create dataframe we need to use dictionary) generate karta hai

In [58]:
pip install pandas

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [59]:
import pandas as pd

In [76]:
list = ['rk' , 'vk' , 'ak' , 'bk']
s=pd.Series(list) #  Create a Series
s=pd.Series(list , index=['a', 'b', 'c', 'd']) #  Create a Series with custom index
print(s)

a    rk
b    vk
c    ak
d    bk
dtype: object

In [61]:
d = {
    "RollNo" : [1,2,3,4,5 ,6,7],
    "name" : ['rk' , 'vk' ,'sk', 'ak' , 'bk' , 'ck' ,'dk'] ,
    "marks" : [56 , 80 , 70 , 60 ,50 , 90 , 100] ,
    "branch" : ["cs" , "cs" , "DS" ,"DS" , "cs" , "cs" , "DS"]
}
print(d)
print(type(d))
df = pd.DataFrame(d) #  Create a DataFrame
print(df)

{'RollNo': [1, 2, 3, 4, 5, 6, 7], 'name': ['rk', 'vk', 'sk', 'ak', 'bk', 'ck', 'dk'], 'marks': [56, 80, 70, 60, 50, 90, 100], 'branch': ['cs', 'cs', 'DS', 'DS', 'cs', 'cs', 'DS']}
<class 'dict'>
   RollNo name  marks branch
0       1   rk     56     cs
1       2   vk     80     cs
2       3   sk     70     DS
3       4   ak     60     DS
4       5   bk     50     cs
5       6   ck     90     cs
6       7   dk    100     DS

In [62]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\asus\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asus\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [63]:
import pandas as pd
%pip install openpyxl
import openpyxl

Requirement already satisfied: openpyxl in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
df = pd.read_excel(r"./PandasEx.xlsx")
print(df)

       Name  Class  Subject  Marks Gender
0   Harshit     10     Math    100      M
1    Jaidev      8     Math     95      F
2     Maddy      7     Math     85      F
3    Sakshi      9     Math     45      M
4    Kumkum      5     Math     67      F
5     Kirti     10  Science     87      M
6     Achal     10  Science     89      M
7    Khushi      8  Science     88      F
8    Gautam      9  Science     34      F
9       Ram     10  Science     56      M
10     Riya      9     Math     76      M
11    Parul      7     Math     52      F
12     Pari      9     Math     32      F
13  Pushkar      4  Science     45      M
14  Prabhat     10     Math     98      M
15   Ashish     10  Science     76      F
16     Ravi      8     Math     92      M
17    Rishi     10     Math     94      M
18    Meenu     10  Science     56      F

In [65]:
# starting ke 5 element fetch karna hai

df.head(5)

      Name  Class Subject  Marks Gender
0  Harshit     10    Math    100      M
1   Jaidev      8    Math     95      F
2    Maddy      7    Math     85      F
3   Sakshi      9    Math     45      M
4   Kumkum      5    Math     67      F

In [66]:
# end record ke 5 element fetch karna hai

df.tail(5)

       Name  Class  Subject  Marks Gender
14  Prabhat     10     Math     98      M
15   Ashish     10  Science     76      F
16     Ravi      8     Math     92      M
17    Rishi     10     Math     94      M
18    Meenu     10  Science     56      F

In [67]:
# fecth specific column

print(df['Subject'])

0        Math
1        Math
2        Math
3        Math
4        Math
5     Science
6     Science
7     Science
8     Science
9     Science
10       Math
11       Math
12       Math
13    Science
14       Math
15    Science
16       Math
17       Math
18    Science
Name: Subject, dtype: object

In [68]:
df.head()
df.tail()
print(df['Name'].head())

0    Harshit
1     Jaidev
2      Maddy
3     Sakshi
4     Kumkum
Name: Name, dtype: object

In [ ]:
df.describe() # used to calculate the statistical summary.

           Class       Marks
count  19.000000   19.000000
mean    8.578947   71.947368
std     1.773753   22.709454
min     4.000000   32.000000
25%     8.000000   54.000000
50%     9.000000   76.000000
75%    10.000000   90.500000
max    10.000000  100.000000

In [70]:
df.shape

(19, 5)

In [71]:
print(df[['Name', 'Class', 'Subject', 'Marks', 'Gender']])

       Name  Class  Subject  Marks Gender
0   Harshit     10     Math    100      M
1    Jaidev      8     Math     95      F
2     Maddy      7     Math     85      F
3    Sakshi      9     Math     45      M
4    Kumkum      5     Math     67      F
5     Kirti     10  Science     87      M
6     Achal     10  Science     89      M
7    Khushi      8  Science     88      F
8    Gautam      9  Science     34      F
9       Ram     10  Science     56      M
10     Riya      9     Math     76      M
11    Parul      7     Math     52      F
12     Pari      9     Math     32      F
13  Pushkar      4  Science     45      M
14  Prabhat     10     Math     98      M
15   Ashish     10  Science     76      F
16     Ravi      8     Math     92      M
17    Rishi     10     Math     94      M
18    Meenu     10  Science     56      F

In [72]:
# condition

df[df['Marks']>70]

       Name  Class  Subject  Marks Gender
0   Harshit     10     Math    100      M
1    Jaidev      8     Math     95      F
2     Maddy      7     Math     85      F
5     Kirti     10  Science     87      M
6     Achal     10  Science     89      M
7    Khushi      8  Science     88      F
10     Riya      9     Math     76      M
14  Prabhat     10     Math     98      M
15   Ashish     10  Science     76      F
16     Ravi      8     Math     92      M
17    Rishi     10     Math     94      M

In [73]:
df[(df['Marks']>85) & (df['Class']==10)]

       Name  Class  Subject  Marks Gender
0   Harshit     10     Math    100      M
5     Kirti     10  Science     87      M
6     Achal     10  Science     89      M
14  Prabhat     10     Math     98      M
17    Rishi     10     Math     94      M